### ISSUE TITLE
uses pkg `spinlock-rs` as `spinlock`, but its name is `spin`

### ISSUE THREAD

**Issue by tbg** [phil-opp/rustos-experiment#5]
``` bash
✔ ~/rust/rustos-experiment [master|✔]
21:09 $ cargo build
    Updating git repository `https://github.com/phil-opp/spinlock-rs.git`
no matching package named `spinlock` found (required by `rustos`)
location searched: https://github.com/phil-opp/spinlock-rs.git?branch=try_lock
version required: *
```

https://github.com/phil-opp/spinlock-rs/blob/try_lock/Cargo.toml:

```
[package]

name = "spin"
```

**Comment by phil-opp** [comment]
Thanks! But I won't contiunue this project as it was just an experiment. Check out [blog_os](https://github.com/phil-opp/blog_os) for my current Rust OS project. Maybe [rust-os-experiment-2](https://github.com/phil-opp/rust-os-experiment-2) is also interesting, but it's old too and does not compile with recent nightlies.

**Comment by tbg** [comment]
ok, just tried to follow along. Will close.
